### ISSUE TITLE
Older versions of Windows (<6.2)

### ISSUE THREAD

**Issue by unwillinglyawesome** [shawnkhall/Tools#1]
I was wondering if there was a possibility to support older versions of Windows, such as:

`5.1` (Windows XP)
`5.2` (Windows XP x64, Windows Server 2003, Windows Server 2003 R2)
`6.0` (Windows Vista, Windows Server 2008)
`6.1` (Windows 7, Windows Server 2008 R2)

If those are available to download.

P. S. Thank you for your work, much appreciated.

**Comment by unwillinglyawesome** [comment]
I confirm those are available:
```
PS C:\Users\Sergey\Desktop\New folder\Tools> .\ChromeDownloader.ps1 win 32 -os 5.2 -do info
Version: 49.0.2623.112
Url: http://dl.google.com/release2/14okehgrtfipvtyyd9pt7hf7ek7hhs7k47bc481jwgh8fz1ono51hw75dtgcm4j6kkei8h9clijoftygpga0q2kbey0o9n4ec6wd/49.0.2623.112_chrome_installer.exe
File: 49.0.2623.112_chrome_installer.exe
SHA256: 6557a26b9ff6185d2e215ccaf3d64d80a0e65c69ac23a091fc050612724908b8
Size: 45001120
Status: ok
```

**Comment by shawnkhall** [comment]
Thank you for your feedback, @unwillinglyawesome

I'm surprised these are available since they're no longer supported. Nevertheless, I've added 32-bit support for Server 2003 (5.2) through 2008 (6.0) and 32/64-bit support for Server 2008 R2 (6.1)
