### ISSUE TITLE
Invoke-WebRequest can be sped up with variable

### ISSUE THREAD

**Issue by robcmo** [shawnkhall/Tools#6]
Invoke-WebRequest is very slow on PowerShell 5.1, but can be sped up significantly by adding this variable prior to iwr.

``` powershell
Set-Variable ProgressPreference SilentlyContinue
Invoke-WebRequest -Uri "$url$package" -OutFile "$file$ext"
```

**Comment by shawnkhall** [comment]
WOW. That is an insanely better download experience. I'll be adding that into the script in the next couple days. Thank you @robcmo !

**Comment by shawnkhall** [comment]
Added in v3, now available.
