### ISSUE TITLE
What about proxy support

### ISSUE THREAD

**Issue by pethrowilo** [shawnkhall/Tools#7]
```powershell
[System.Net.WebRequest]::DefaultWebProxy = [System.Net.WebRequest]::GetSystemWebProxy()
[System.Net.WebRequest]::DefaultWebProxy.Credentials = [System.Net.CredentialCache]::DefaultNetworkCredentials
```

so it works with environment variables such as `http_proxy`?

**Comment by shawnkhall** [comment]
thank you, @pethrowilo. This is now added in 3.1. Please test and let me know if it works for you.

**Comment by pethrowilo** [comment]
> thank you, @pethrowilo. This is now added in 3.1. Please test and let me know if it works for you.

it works as intended 😄
